apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: vllm
spec:
  selector:
    app: vllm
  ports:
    - port: 80
      targetPort: 8000
      name: http
    - port: 9090
      targetPort: 9090
      name: metrics
  type: ClusterIP
