//! Draft generation strategies.
//!
//! Two implementations:
//! - [`generate_per_seq_drafts`](super::super::Engine::generate_per_seq_drafts) —
//!   v18.0 per-request dispatch via `DraftResolver`. Handles mixed routing
//!   and `degraded_draft` sticky fallback.
//! - [`generate_batched_drafts`](super::super::Engine::generate_batched_drafts) —
//!   Legacy batched single-draft path. All sequences share one draft model.

use crate::error::Result;
use crate::speculative::ResolvedDraft;
use crate::sync::lock_mutex;
use std::panic::{AssertUnwindSafe, catch_unwind};
use vllm_traits::{Batch, TokenId};

impl crate::engine::Engine {
    /// v18.0 per-request draft dispatch via `DraftResolver`.
    ///
    /// For each seq in the batch:
    /// 1. Skip if `sequence.degraded_draft` (FALL-02 sticky flag) — return
    ///    empty drafts so the seq falls through to non-spec decode.
    /// 2. Resolve via `resolver.resolve(seq.draft_model_id)` → picks the
    ///    named external draft, the self-spec fallback, or None.
    /// 3. Run the resolved backend's forward per position (up to `max_draft`).
    /// 4. Catch per-seq forward errors → set `degraded_draft = true` on that
    ///    sequence and increment `inc_draft_runtime_error`. Future steps skip
    ///    this seq's draft.
    ///
    /// Returns `Vec<Vec<TokenId>>` in the same shape as `generate_batched_drafts`
    /// so the downstream verification path is unchanged.
    pub(crate) fn generate_per_seq_drafts(
        &mut self,
        batch: &Batch,
        max_draft: usize,
    ) -> Vec<Vec<TokenId>> {
        let resolver = self
            .draft_resolver
            .as_ref()
            // invariant: caller contract — `generate_per_seq_drafts` is only invoked when a
            // `DraftResolver` has been installed (see `Engine::with_drafts_boxed` initialization).
            .expect("generate_per_seq_drafts called without draft_resolver");
        let n_seq = batch.seq_ids.len();
        let mut draft_outputs: Vec<Vec<TokenId>> = vec![Vec::with_capacity(max_draft); n_seq];

        for (i, seq_id) in batch.seq_ids.iter().enumerate() {
            // Look up the sequence to check degraded_draft and read draft_model_id.
            let seq_state = self.scheduler.get_sequence(*seq_id);
            let (degraded, draft_model_id): (bool, Option<crate::speculative::DraftId>) =
                match seq_state {
                    Some(s) => (s.degraded_draft, s.draft_model_id.clone()),
                    None => {
                        // Sequence no longer in scheduler — skip (shouldn't happen
                        // in normal flow).
                        continue;
                    }
                };

            if degraded {
                // FALL-02 sticky: this sequence has been degraded. Skip draft
                // generation entirely; the seq falls through to non-spec
                // decode in the verifier path.
                continue;
            }

            let resolution = resolver.resolve(draft_model_id.as_ref());
            let backend = match resolution {
                ResolvedDraft::External(b) | ResolvedDraft::SelfSpec(b) => b,
                ResolvedDraft::None => continue,
            };

            // Per-position draft generation for this single sequence.
            let mut current_tokens: Vec<TokenId> = batch.input_tokens[i].clone();
            // The last input token sits at `num_computed + input_len - 1`;
            // draft j is generated by decoding one token at `base + j` with
            // an advancing `num_computed`, so the draft cache accumulates
            // each accepted draft at its true position (RIL ISS-029). The
            // old code fed the whole growing token list with a constant
            // `num_computed` and `is_prefill=false`: `forward_decode` uses
            // `positions[0]` for RoPE and writes KV at `num_computed`, so
            // every draft was generated at the SAME position from a cache
            // that never accumulated — real-model drafts diverged from the
            // target and were rejected, making speculative decode a no-op.
            let base = batch.num_computed_tokens[i] + batch.input_tokens[i].len().saturating_sub(1);
            // Run one EXTRA iteration so the last draft's KV is written into
            // the draft cache (its predicted token is discarded). Without it,
            // the final draft's slot stays uninitialised and the NEXT step's
            // generation reads a zero gap, diverging from the target context
            // (RIL ISS-029).
            for pos in 0..=max_draft {
                let Some(&token) = current_tokens.last() else {
                    break;
                };
                let draft_pos = base + pos;
                let step_tokens = vec![token];
                let step_positions = vec![draft_pos];
                let step_num_computed = [draft_pos];
                let step_is_prefill = [false];
                // `AssertUnwindSafe` is required because the closure captures
                // `backend: Arc<Mutex<Box<dyn ModelBackend>>>` along with the
                // `current_tokens` buffer. The standard
                // `UnwindSafe` bound would refuse to compile even though the
                // catch is a deliberate guard against panics in foreign
                // backend code. If a panic occurs mid-forward, the backend's
                // internal state (KV cache, allocator) may be partially
                // mutated and the Mutex may become poisoned — subsequent
                // locks will themselves panic and be re-caught here. Note:
                // `catch_unwind` cannot catch aborts (e.g. double-panic,
                // `extern "C"` unwinding) — a misbehaving backend could still
                // crash the engine.
                let result = catch_unwind(AssertUnwindSafe(|| {
                    // invariant: lock is only held for synchronous field access; no panic possible while holding.
                    let mut guard = backend.lock().expect("draft backend mutex poisoned");
                    guard.forward(
                        &[*seq_id],
                        std::slice::from_ref(&step_tokens),
                        std::slice::from_ref(&step_positions),
                        std::slice::from_ref(&batch.kv_block_ids[i]),
                        &step_num_computed,
                        &step_is_prefill,
                    )
                }));

                #[allow(clippy::option_if_let_else)]
                let forward_result = match result {
                    Ok(r) => r,
                    Err(_) => {
                        // Panic in draft forward — treat as runtime error.
                        Err(vllm_traits::ModelError::new("draft forward panicked"))
                    }
                };

                match forward_result {
                    Ok(output) => {
                        if let Some(sampled) = output.next_tokens.first() {
                            let token = sampled.token;
                            if pos >= max_draft {
                                // Extra iteration: the KV was written, but the
                                // prediction itself is not a draft.
                                break;
                            }
                            draft_outputs[i].push(token);
                            current_tokens.push(token);
                        } else {
                            // Empty output — stop draft generation for this seq.
                            break;
                        }
                    }
                    Err(e) => {
                        // FALL-02: draft forward error → mark degraded and skip
                        // future drafts for this seq.
                        tracing::warn!(
                            seq_id = %seq_id,
                            error = %e,
                            "draft forward failed; marking sequence degraded"
                        );
                        self.scheduler.metrics.inc_draft_runtime_error();
                        if let Some(s) = self.scheduler.get_sequence_mut(*seq_id) {
                            s.degraded_draft = true;
                        }
                        break;
                    }
                }
            }
        }

        draft_outputs
    }

    /// Batched per-position draft generation (Plan 17.1-B).
    ///
    /// All sequences generate draft position k before advancing to k+1.
    pub(crate) fn generate_batched_drafts(
        &self,
        batch: &Batch,
        max_draft: usize,
    ) -> Result<Vec<Vec<TokenId>>> {
        let n_seq = batch.seq_ids.len();
        let mut draft_outputs: Vec<Vec<TokenId>> = vec![Vec::with_capacity(max_draft); n_seq];

        let draft_model = if let Some(dm) = &self.draft_model {
            dm.clone()
        } else {
            tracing::warn!("No draft model set, returning empty drafts");
            return Ok(draft_outputs);
        };

        // Per-sequence state tracking: current input tokens (the draft cache
        // advances via `num_computed`; positions are derived per step).
        let mut current_tokens: Vec<Vec<TokenId>> = batch.input_tokens.clone();

        // Run one EXTRA iteration so the last draft's KV is written into the
        // draft cache (its predicted token is discarded) — see the per-seq
        // loop for the rationale (RIL ISS-029).
        for pos in 0..=max_draft {
            // Build per-position batch
            let mut pos_seq_ids = Vec::with_capacity(n_seq);
            let mut pos_input_tokens = Vec::with_capacity(n_seq);
            let mut pos_positions = Vec::with_capacity(n_seq);
            let mut pos_kv_block_ids = Vec::with_capacity(n_seq);
            let mut pos_num_computed = Vec::with_capacity(n_seq);
            let mut pos_is_prefill = Vec::with_capacity(n_seq);
            let mut active_indices = Vec::with_capacity(n_seq);

            for (i, seq_id) in batch.seq_ids.iter().enumerate() {
                if current_tokens[i].is_empty() {
                    continue;
                }
                pos_seq_ids.push(*seq_id);
                // RIL ISS-029: feed only the LAST token at its true position
                // with advancing `num_computed` (see `generate_per_seq_drafts`
                // for the full rationale). Draft j decodes one token at
                // `base + j` so the draft cache accumulates at true
                // positions; the old code passed the whole growing token
                // list with constant `num_computed`, generating every draft
                // at the same position from a cache that never accumulated —
                // real-model drafts were rejected and speculative decode was
                // a no-op.
                let Some(&token) = current_tokens[i].last() else {
                    continue;
                };
                let base =
                    batch.num_computed_tokens[i] + batch.input_tokens[i].len().saturating_sub(1);
                let draft_pos = base + pos;
                pos_input_tokens.push(vec![token]);
                pos_positions.push(vec![draft_pos]);
                pos_kv_block_ids.push(batch.kv_block_ids[i].clone());
                pos_num_computed.push(draft_pos);
                pos_is_prefill.push(false);
                active_indices.push(i);
            }

            if pos_seq_ids.is_empty() {
                break;
            }

            // Single forward pass per position across all active sequences
            let result = lock_mutex(&draft_model)?.forward(
                &pos_seq_ids,
                &pos_input_tokens,
                &pos_positions,
                &pos_kv_block_ids,
                &pos_num_computed,
                &pos_is_prefill,
            );
            let output = match result {
                Ok(o) => o,
                Err(e) => {
                    tracing::warn!(error = %e, pos = pos, "Draft model forward failed at position");
                    break;
                }
            };

            // Distribute output tokens back to per-sequence drafts
            for (j, &seq_idx) in active_indices.iter().enumerate() {
                let token = output.next_tokens.get(j).map_or(0, |sampled| sampled.token);
                if pos >= max_draft {
                    // Extra iteration: KV written, prediction discarded.
                    continue;
                }
                draft_outputs[seq_idx].push(token);
                current_tokens[seq_idx].push(token);
            }
        }

        Ok(draft_outputs)
    }
}

/// argmax: argmax helper used by the verifier path.
///
/// Tie-breaks to the FIRST max index to stay consistent with
/// [`vllm_traits::argmax_logits`] (the single source of truth for
/// greedy decoding). The two functions must agree on ties: the
/// verifier's temperature-aware path can fall through to either
/// depending on `params.temperature`, and a tie-break mismatch
/// would silently change the accepted draft sequence under
/// temperature == 0 when several logits share the maximum.
#[allow(dead_code)] // historical export; the verifier now delegates to sample_one_with_params directly (P36)
pub fn argmax(logits: &[f32]) -> TokenId {
    let mut best_idx = 0_usize;
    let mut best_val = f32::NEG_INFINITY;
    for (i, &v) in logits.iter().enumerate() {
        if v > best_val {
            best_idx = i;
            best_val = v;
        }
    }
    TokenId::try_from(best_idx).unwrap_or(0)
}
