//! Engine lifecycle methods: health checks, error state, cancel handling, and `add_request`.
//!
//! The main run loop is `engine/run.rs`; this file is the supporting
//! surface that callers and tests poke at directly.

// Sub-module for health, error, cancel, and add_request methods on Engine.
// See mod.rs for the Engine struct definition.

use crate::engine::Engine;
use crate::types::Request;
use tokio::sync::mpsc;
use vllm_traits::{FinishReason, SampledToken, SeqId};

impl Engine {
    /// Returns `true` if the engine is considered healthy and ready to process
    /// requests. The current heuristic treats an engine as unhealthy once it has
    /// accumulated 10 or more errors — callers should stop issuing new requests
    /// and may want to inspect [`Engine::get_last_error`] for diagnostics.
    pub const fn is_healthy(&self) -> bool {
        self.error_count < 10
    }

    /// Returns the most recent error message recorded by the engine, or `None`
    /// if no error has occurred since the engine was constructed.
    ///
    /// This is a lightweight accessor intended for health probes and CLI status
    /// reporting. It does not clear the error; subsequent errors overwrite the
    /// stored value.
    pub fn get_last_error(&self) -> Option<&str> {
        self.last_error.as_deref()
    }

    /// Notify any registered handler of the [`FinishReason`] for `seq_id`,
    /// then drop both the finish-reason sender and the matching token
    /// response channel.
    ///
    /// Used by the regular and speculative step paths (`scheduler/batch.rs`,
    /// `engine/spec_dispatch/dispatch.rs`, `engine/graph_step.rs`) just
    /// before they drop `response_txs`. Centralising the helper keeps
    /// the three sites consistent — pre-fix each one dropped the
    /// channel without telling the handler *why*, and the HTTP layer
    /// hardcoded `finish_reason = "stop"` for every response.
    ///
    /// The `send` is best-effort: if the handler already dropped the
    /// oneshot (e.g. it gave up waiting after a client disconnect),
    /// the `Result` is ignored.
    pub(crate) fn finalize_finished(&mut self, seq_id: SeqId, reason: FinishReason) {
        if let Some(tx) = self.finish_reason_txs.remove(&seq_id) {
            let _ = tx.send(reason);
        }
        self.response_txs.remove(&seq_id);
    }

    /// Cancel an in-flight or queued request identified by `seq_id`.
    ///
    /// Returns `true` if a request with that id was found and removed from the
    /// scheduler (and its response channel was dropped), `false` otherwise. The
    /// caller is responsible for sending any partial-result notifications to
    /// the client before invoking this method; once cancelled, no further
    /// tokens will be produced for the sequence.
    ///
    /// If the cancelled sequence had a `finish_reason_tx` registered
    /// (i.e. the HTTP layer asked for one), this method sends
    /// [`FinishReason::Cancelled`] through it before removing the
    /// channel — so the handler can distinguish "client cancelled"
    /// from a channel close that happened for some other reason.
    pub fn cancel_request(&mut self, seq_id: SeqId) -> bool {
        let canceled = self.scheduler.cancel_request(seq_id);
        if canceled {
            self.finalize_finished(seq_id, FinishReason::Cancelled);
            self.scheduler.metrics.remove_per_request(seq_id);
        }
        canceled
    }

    /// Submit a new generation request to the engine.
    ///
    /// The returned `SeqId` can be used with [`Engine::cancel_request`] or for
    /// correlation with tokens emitted on `response_tx`. Tokens generated by
    /// the model for this request will be sent on `response_tx` as they are
    /// produced; the channel must remain open for the lifetime of the request.
    ///
    /// If `req.prompt` is empty the request is rejected: `last_error` is set
    /// and `0` is returned. (Sequence id 0 is reserved as a sentinel for the
    /// "no request allocated" case.)
    ///
    /// **No `FinishReason` notification**: this method does not accept a
    /// finish-reason oneshot. Callers that need the OpenAI-correct
    /// `finish_reason` (HTTP streaming handlers) should send an
    /// `EngineMessage::AddRequest` over the engine mailbox instead — the
    /// message variant carries the optional `finish_reason_tx` field. Tests
    /// and other in-process callers that talk to the engine directly don't
    /// need it: when the response channel closes without a reason, the
    /// caller falls back to `"stop"`.
    ///
    /// **P36 v0.3 wire-type follow-up engine wire-through:**
    /// `response_tx` carries [`SampledToken`] (token + logprob +
    /// top_logprobs) instead of a bare `TokenId` so the HTTP layer
    /// can render OpenAI's `choices[].logprobs` shape.
    pub fn add_request(&mut self, req: Request, response_tx: mpsc::Sender<SampledToken>) -> SeqId {
        // Validate prompt is not empty
        if req.prompt.is_empty() {
            self.last_error = Some("prompt cannot be empty".to_string());
            return 0;
        }

        let seq_id = self.scheduler.add_request(req);
        self.response_txs.insert(seq_id, response_tx);
        seq_id
    }
}
