// Sub-module for health, error, cancel, and add_request methods on Engine.
// See mod.rs for the Engine struct definition.

use crate::engine::Engine;
use crate::types::Request;
use tokio::sync::mpsc;
use vllm_traits::{SeqId, TokenId};

impl Engine {
    /// Returns `true` if the engine is considered healthy and ready to process
    /// requests. The current heuristic treats an engine as unhealthy once it has
    /// accumulated 10 or more errors — callers should stop issuing new requests
    /// and may want to inspect [`Engine::get_last_error`] for diagnostics.
    pub const fn is_healthy(&self) -> bool {
        self.error_count < 10
    }

    /// Returns the most recent error message recorded by the engine, or `None`
    /// if no error has occurred since the engine was constructed.
    ///
    /// This is a lightweight accessor intended for health probes and CLI status
    /// reporting. It does not clear the error; subsequent errors overwrite the
    /// stored value.
    pub fn get_last_error(&self) -> Option<&str> {
        self.last_error.as_deref()
    }

    /// Cancel an in-flight or queued request identified by `seq_id`.
    ///
    /// Returns `true` if a request with that id was found and removed from the
    /// scheduler (and its response channel was dropped), `false` otherwise. The
    /// caller is responsible for sending any partial-result notifications to
    /// the client before invoking this method; once cancelled, no further
    /// tokens will be produced for the sequence.
    pub fn cancel_request(&mut self, seq_id: SeqId) -> bool {
        let canceled = self.scheduler.cancel_request(seq_id);
        if canceled {
            self.response_txs.remove(&seq_id);
            self.scheduler.metrics.remove_per_request(seq_id);
        }
        canceled
    }

    /// Submit a new generation request to the engine.
    ///
    /// The returned `SeqId` can be used with [`Engine::cancel_request`] or for
    /// correlation with tokens emitted on `response_tx`. Tokens generated by
    /// the model for this request will be sent on `response_tx` as they are
    /// produced; the channel must remain open for the lifetime of the request.
    ///
    /// If `req.prompt` is empty the request is rejected: `last_error` is set
    /// and `0` is returned. (Sequence id 0 is reserved as a sentinel for the
    /// "no request allocated" case.)
    pub fn add_request(&mut self, req: Request, response_tx: mpsc::Sender<TokenId>) -> SeqId {
        // Validate prompt is not empty
        if req.prompt.is_empty() {
            self.last_error = Some("prompt cannot be empty".to_string());
            return 0;
        }

        let seq_id = self.scheduler.add_request(req);
        self.response_txs.insert(seq_id, response_tx);
        seq_id
    }
}
