#!/bin/sh
[ "$HUSKY" = "0" ] && exit 0

echo "Running pre-commit checks..."

just fmt-check
if [ $? -ne 0 ]; then
    echo "Code is not formatted. Run: cargo fmt --all"
    exit 1
fi

echo "Pre-commit checks passed"
